volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    container_name: db
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: nenfind/foodgram_backend:latest
    container_name: backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/backend/media
  frontend:
    image: nenfind/foodgram_frontend:latest
    container_name: frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  gateway:
    image: nenfind/foodgram_gateway:latest
    container_name: gateway
    depends_on:
      - backend
      - frontend
    env_file: .env
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/static
      - media_volume:/app/backend/media
    ports:
      - 8000:80