# Generated by Django 5.1.1 on 2025-05-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.SlugField(default='siu7U7xc8FkLr9mwnkXduY', help_text='Короткая неизменяющаяся ссылка', max_length=256, verbose_name='короткая ссылка'),
        ),
    ]
