# Generated by Django 5.1.1 on 2025-05-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_short_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.SlugField(default='sYdBoNVe9oLjBXYwJp5N2Z', help_text='Короткая неизменяющаяся ссылка', max_length=256, unique=True, verbose_name='короткая ссылка'),
        ),
    ]
