# Generated by Django 5.1.1 on 2025-05-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_link',
            field=models.SlugField(blank=True, help_text='Короткая неизменяющаяся ссылка', max_length=256, unique=True, verbose_name='короткая ссылка'),
        ),
    ]
