# Generated by Django 5.1 on 2025-06-12 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_short_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('pub_date', 'name'), 'verbose_name': 'рецепт', 'verbose_name_plural': 'рецепты'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 12, 8, 5, 43, 442565, tzinfo=datetime.timezone.utc), verbose_name='дата публикации'),
            preserve_default=False,
        ),
    ]
